tienda_app/urls.py
from django.contrib import admin
from django.urls import path , include

from .router import router


from .views import      TiendaListView   \
                    ,   TiendaDetailView \
                    ,   TiendaCreateView \
                    ,   TiendaUpdateView \
                    ,   TiendaDeleteView

app_name = "tienda"

urlpatterns = [
    path("", TiendaListView.as_view(), name="all"),
    path("create/", TiendaCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", TiendaDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", TiendaUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", TiendaDeleteView.as_view(), name="delete")
]

urlpatterns += router.urls

tiendas_manager/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from .views import Index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", Index.as_view(), name="index"),
    path("tienda/", include("tienda_app.urls"))
]

tienda_app/models.py
from django.db import models
from django.db.models import Model


# Create your models here.
class Tienda(Model):
    """
    Atributos de clase que son usadas por herencia de la clase Model
    """

    nombre = models.CharField(max_length=100, default="Tienda x")
    rubro = models.CharField(max_length=100, default="rubro x", blank=False, null=False)
    contacto = models.EmailField(max_length=100, default="no_contact@mail.com")
    ubicacion = models.CharField(max_length=100, default="Tienda online")
    fecha_habilitacion = models.DateField(blank=False, null=False, auto_now=True)

    # podemos crear la tabla con un nombre especifico pero se lo tenemos
    # que indicar directamente en la metaclase

    class Meta:
       db_table = "tiendas_buenos_aires_arg"


    def __str__(self):
        return f"El nombre de la tienda: {self.nombre} rubro: {self.rubro}"

    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]


# -> Next registrar modelo admin.py

tienda_app/views.py
from django.urls import reverse_lazy
from django.views import View

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, UpdateView, CreateView


from .models import Tienda

# Create your views here.


class TiendaBaseView(View):
    template_name = 'tienda.html'
    model = Tienda
    fields = '__all__'
    success_url = reverse_lazy('tienda:all')


class TiendaListView(TiendaBaseView,ListView):
    """
    ESTO ME PERMITE CREAR UNA VISTA CON LOS Tienda
    """

class TiendaDetailView(TiendaBaseView,DetailView):
    template_name = "tienda_detail.html"

class TiendaCreateView(TiendaBaseView,CreateView):
    template_name = "tienda_create.html"
    extra_context = {
        "tipo": "Crear tienda"
    }

class TiendaUpdateView(TiendaBaseView,UpdateView):
    template_name = "tienda_create.html"
    extra_context = {
        "tipo": "Actualizar tienda"
    }

class TiendaDeleteView(TiendaBaseView,DeleteView):
    template_name = "tienda_delete.html"
    extra_context = {
        "tipo": "Borrar tienda"
    }

tiendas_manager/views.py
from django.views.generic import TemplateView


class Index(TemplateView):
    extra_context = {"comision": "23508"}
    template_name = "index.html"

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static './css/style.css' %}" />
    <title>Segunda Parte Django</title>
  </head>

  <body>
    <div class="loader">
      <div class="balls"></div>
    </div>

    <header class="header" id="header">
      <nav class="navbar">
        <a href="#top" class="brand">
          <div class="logo"><i class="fa fa-rocket"></i></div>
          <h3>{{comision}}</h3>
        </a>
        <div class="burger" id="burger">
          <span class="burger-line"></span>
          <span class="burger-line"></span>
          <span class="burger-line"></span>
        </div>
        <span class="overlay"></span>
        <div class="menu" id="menu">
          <ul class="menu-inner">
            <li class="menu-item">
              <a class="menu-link" href="{% url 'index' %}">Store Manager</a>
            </li>
            <li class="menu-item">
              <a class="menu-link" href="{% url 'tienda:all' %}">CRUD STORES</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    {% block content %} {% endblock %}
  </body>
  <script src=" https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js "></script>
  <script src="{% static './js/index.js' %}"></script>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="particles-js"></div>

<section class="hero" id="top">
    <div class="title">
        <h1 class="intro">
            <span class="magic">
                <span class="magic-star">
                    <svg viewBox="0 0 512 512">
                        <path
                            d="M512 255.1c0 11.34-7.406 20.86-18.44 23.64l-171.3 42.78l-42.78 171.1C276.7 504.6 267.2 512 255.9 512s-20.84-7.406-23.62-18.44l-42.66-171.2L18.47 279.6C7.406 276.8 0 267.3 0 255.1c0-11.34 7.406-20.83 18.44-23.61l171.2-42.78l42.78-171.1C235.2 7.406 244.7 0 256 0s20.84 7.406 23.62 18.44l42.78 171.2l171.2 42.78C504.6 235.2 512 244.6 512 255.1z" />
                    </svg>
                </span>
                <span class="magic-star">
                    <svg viewBox="0 0 512 512">
                        <path
                            d="M512 255.1c0 11.34-7.406 20.86-18.44 23.64l-171.3 42.78l-42.78 171.1C276.7 504.6 267.2 512 255.9 512s-20.84-7.406-23.62-18.44l-42.66-171.2L18.47 279.6C7.406 276.8 0 267.3 0 255.1c0-11.34 7.406-20.83 18.44-23.61l171.2-42.78l42.78-171.1C235.2 7.406 244.7 0 256 0s20.84 7.406 23.62 18.44l42.78 171.2l171.2 42.78C504.6 235.2 512 244.6 512 255.1z" />
                    </svg>
                </span>
                <span class="magic-star">
                    <svg viewBox="0 0 512 512">
                        <path
                            d="M512 255.1c0 11.34-7.406 20.86-18.44 23.64l-171.3 42.78l-42.78 171.1C276.7 504.6 267.2 512 255.9 512s-20.84-7.406-23.62-18.44l-42.66-171.2L18.47 279.6C7.406 276.8 0 267.3 0 255.1c0-11.34 7.406-20.83 18.44-23.61l171.2-42.78l42.78-171.1C235.2 7.406 244.7 0 256 0s20.84 7.406 23.62 18.44l42.78 171.2l171.2 42.78C504.6 235.2 512 244.6 512 255.1z" />
                    </svg></span>

                <span class="magic-text">Codo a Codo </span></span> Comisión {{comision}}
        </h1>
    </div>
</section>

<section class="section">
    <div class="desktop-wrapper">
        <div class="carousel reflect">
            <ul class="carousel__list" data-aos="fade-up" data-aos-duration="1000" data-aos-easing="ease">
                <li class="carousel__item" data-pos="-2"></li>
                <li class="carousel__item" data-pos="-1"></li>
                <li class="carousel__item" data-pos="0"></li>
                <li class="carousel__item" data-pos="1"></li>
                <li class="carousel__item" data-pos="2"></li>
            </ul>
        </div>
    </div>
</section>

{% endblock %}

tienda_app/templates/tienda.html
{% extends 'base.html' %} {% load static %} {% block content %}

<main>
  <div>
    <h2>Tiendas</h2>
    <h3><a href="{% url 'tienda:create' %}">Crear un tienda</a></h3>
    <div class="list">
      {% for tienda in tienda_list %}
      <fieldset>
        <legend>Nombre: {{tienda.nombre}}</legend>
        <ul>
          <li>Direccion de la tienda : {{tienda.ubicacion}}</li>
          <li>Contacto: {{tienda.contacto}}</li>
          <li>Rubro: {{tienda.rubro}}</li>
          <li>Decha de alta : {{tienda.fecha_habilitacion}}</li>
        </ul>

        <div>
          <a href="{% url 'tienda:detail' tienda.id  %}">
            Detalle de {{tienda.nombre}} 🟢</a
          >
        </div>
        <div>
          <a href="{% url 'tienda:delete' tienda.id %}"
            >Borrar {{tienda.nombre }} ❌</a
          >
        </div>
        <div>
          <a href="{% url 'tienda:update' tienda.id %}"
            >Editar {{tienda.nombre }}📋</a
          >
        </div>
      </fieldset>
      {% endfor %}
    </div>
  </div>
</main>
{% endblock %}

tienda_app/templates/tienda_create.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main>
  <div>
    <form method="post">
      {% csrf_token %} {{form.as_div}}
      <input type="submit" value="{{ tipo }}" />
    </form>

    <a href="{% url 'tienda:all' %}">Volvamos a las tiendas</a>
  </div>
</main>
{% endblock %}

tienda_app/templates/tienda_delete.html
{% extends 'base.html' %} {% load static %} {% block content %}

<main>
  <div>
    <h2>Estas seguro que deseas borrar esta tienda?</h2>
    <h2>{{tienda.nombre}}</h2>
    <form method="post">
      {% csrf_token %} {{form.as_p}}
      <input type="submit" value="{{ tipo }}" />
    </form>

    <a href="{% url 'tienda:all' %}">Cancelar borrado</a>
  </div>
</main>

{% endblock %}

tienda_app/templates/tienda_detail.html
{% extends 'base.html' %} {% block content %}

<main>
  <div>
    <h1>{{tienda.nombre}}</h1>
    {% for label, value in tienda.get_fields %}
    <div>
      <span>{{label | upper}}</span>
      <span> <i> {{value}} </i> </span>
    </div>

    {% endfor %}

    <a href="{% url 'tienda:all' %}">Ir al inicio</a>
  </div>
</main>

{% endblock%}